### ISSUE TITLE
What is the API rate limit?

### ISSUE THREAD

**Issue by Kjoedicker** [meetDeveloper/googleDictionaryAPI#73]
I keep getting blocked by the API rate limit. I have come back after a minute or so and been allowed to make requests. Other times I have come back after 15-30 minutes and the block is still up. I'm not making thousands of requests, only 2-3 here and there to test my application.  

What is the threshold for consecutive requests?

**Comment by meetDeveloper** [comment]
@Kjoedicker,  @dxs5670, @mascode, @RajaSrinivasan, @TheoSeo93, @Narayanbhat166, @Trixter9994, @adityaspt, @nvngoc2409, and @YevheniiStepaniuk.

The Rate limit for API is around 200 request per minute. Though due to a problem it use to give 429 without even consumer of the API hitting this limit, I have fixed this issue and you guys will face extremely less Rate Limit error from now on.

Sorry for the inconvenience, I am currently making many changes to the API internally to increase its stability and response time and hopefully in near future, the API will be much more robust and performant.

Thank you for using this API, It really feels good when people uses the thing that you designed and use that to build their own software. :) Thank you.

**Comment by meetDeveloper** [comment]
It's actually 300 request per 5 minutes.

**Comment by traderjosh** [comment]
Is a 429 status code returned for reaching the rate limit?

If in my app, I'm making the client call your api, the rate limit belongs to him right? So 50 people using the app at the same time calling the API won't cause my rate limit to expand... you understand?

**Comment by rutikwankhade** [comment]
> It's actually 300 request per 5 minutes.

I also have the same doubt. the limit is for the user's IP address right?
https://github.com/meetDeveloper/freeDictionaryAPI/issues/73#issuecomment-745311419

**Comment by HappyNinja2** [comment]
@meetDeveloper  Can I host the app on different servers and bypass the limit? Does Google limit the rate based on IP to prevent scraping of words?
